splashutils: fbsplash.h File Reference
fbsplash.h File Reference
#include <stdbool.h>
#include <stdio.h>
#include <linux/kd.h>
#include <linux/input.h>
Classes
struct fbspl_cfg_t
Defines
#define FBSPLASH_DIR "@libdir@/splash"
#define FBSPLASH_CACHEDIR FBSPLASH_DIR"/cache"
#define FBSPLASH_PIDFILE FBSPLASH_CACHEDIR"/daemon.pid"
#define FBSPLASH_PROFILE FBSPLASH_CACHEDIR"/profile"
#define FBSPLASH_DAEMON "@sbindir@/fbsplashd.static"
#define FBSPLASH_FIFO FBSPLASH_CACHEDIR"/.splash"
#define FBSPL_THEME_DIR "@themedir@"
#define FBSPL_DEFAULT_THEME "default"
#define FBSPL_PROGRESS_MAX 0xffff
#define FBSPL_EFF_NONE 0
#define FBSPL_EFF_FADEIN 1
#define FBSPL_EFF_FADEOUT 2
#define FBSPL_VERB_QUIET 0
#define FBSPL_VERB_NORMAL 1
#define FBSPL_VERB_HIGH 2
#define FBSPL_MODE_OFF 0x00
#define FBSPL_MODE_VERBOSE 0x01
#define FBSPL_MODE_SILENT 0x02
Enumerations
enum fbspl_type_t {
fbspl_undef, fbspl_bootup, fbspl_reboot, fbspl_shutdown,
fbspl_suspend, fbspl_resume
}
Functions
fbspl_cfg_t * fbsplash_lib_init (fbspl_type_t type)
int fbsplash_lib_cleanup (void)
int fbsplash_parse_kcmdline (bool sysmsg)
void fbsplash_get_res (const char *theme, int *xres, int *yres)
int fbsplash_profile (const char *fmt,...)
bool fbsplash_is_silent (void)
int fbsplash_set_verbose (int old_tty)
int fbsplash_set_silent (void)
void fbsplash_acc_theme_set (const char *theme)
void fbsplash_acc_message_set (const char *msg)
void fbsplash_acc_xservice_set (const char *service)
int fbsplash_set_evdev (void)
int fbsplash_check_daemon (int *pid_daemon)
int fbsplash_check_sanity (void)
int fbsplash_cache_prep (void)
int fbsplash_cache_cleanup (char **profile_save)
int fbsplash_send (const char *fmt,...)
int fbsplashr_init (bool create)
void fbsplashr_cleanup (void)
int fbsplashr_render_buf (struct fbspl_theme *theme, void *buffer, bool repaint)
int fbsplashr_render_screen (struct fbspl_theme *theme, bool repaint, bool bgnd, char effects)
struct fbspl_theme * fbsplashr_theme_load ()
void fbsplashr_theme_free (struct fbspl_theme *theme)
int fbsplashr_tty_silent_init (bool clean)
int fbsplashr_tty_silent_cleanup (void)
int fbsplashr_tty_silent_set (int tty)
int fbsplashr_tty_silent_update (void)
void fbsplashr_message_set (struct fbspl_theme *theme, const char *msg)
void fbsplashr_progress_set (struct fbspl_theme *theme, int progress)
int fbsplashr_input_init ()
void fbsplashr_input_cleanup ()
unsigned short fbsplashr_input_getkey (bool block)
Define Documentation
#define FBSPL_DEFAULT_THEME "default"
#define FBSPL_EFF_FADEIN 1
Referenced by fbsplash_parse_kcmdline(), and fbsplashr_render_screen().
#define FBSPL_EFF_FADEOUT 2
Referenced by fbsplash_parse_kcmdline(), and fbsplashr_render_screen().
#define FBSPL_EFF_NONE 0
#define FBSPL_MODE_OFF 0x00
Referenced by fbsplash_parse_kcmdline().
#define FBSPL_MODE_SILENT 0x02
Referenced by fbsplash_parse_kcmdline(), fbsplashr_render_buf(), and fbsplashr_theme_load().
#define FBSPL_MODE_VERBOSE 0x01
Referenced by fbsplash_parse_kcmdline(), and fbsplashr_theme_load().
#define FBSPL_PROGRESS_MAX 0xffff
Referenced by fbsplashr_progress_set().
#define FBSPL_THEME_DIR "@themedir@"
Referenced by fbsplash_get_res(), and fbsplashr_theme_load().
#define FBSPL_VERB_HIGH 2
#define FBSPL_VERB_NORMAL 1
#define FBSPL_VERB_QUIET 0
#define FBSPLASH_CACHEDIR FBSPLASH_DIR"/cache"
Referenced by fbsplash_cache_cleanup(), and fbsplash_cache_prep().
#define FBSPLASH_DAEMON "@sbindir@/fbsplashd.static"
#define FBSPLASH_DIR "@libdir@/splash"
#define FBSPLASH_FIFO FBSPLASH_CACHEDIR"/.splash"
Referenced by fbsplash_send().
#define FBSPLASH_PIDFILE FBSPLASH_CACHEDIR"/daemon.pid"
Referenced by fbsplash_check_daemon().
#define FBSPLASH_PROFILE FBSPLASH_CACHEDIR"/profile"
Referenced by fbsplash_profile().
Enumeration Type Documentation
enum fbspl_type_t
Enumerator:
fbspl_undef
fbspl_bootup
fbspl_reboot
fbspl_shutdown
fbspl_suspend
fbspl_resume
Function Documentation
void fbsplash_acc_message_set (const char * msg)
Accessor function for config.message
Parameters:
msg The new message setting.
References fbspl_cfg_t::message.
Referenced by fbsplash_parse_kcmdline(), and fbsplashr_message_set().
void fbsplash_acc_theme_set (const char * theme)
Accessor function for config.theme
Parameters:
theme The new theme setting.
References fbspl_cfg_t::theme.
Referenced by fbsplash_parse_kcmdline().
void fbsplash_acc_xservice_set (const char * service)
Accessor function for config.xservice
Parameters:
service The name of the new X service.
References fbspl_cfg_t::xservice.
int fbsplash_cache_cleanup (char ** profile_save)
Clean the splash cache.
Parameters:
profile_save A strlist of files that should be saved to the hdd if profiling is enabled.
Returns:
0 if the splash cache was cleaned, a negative value in case of an error.
References FBSPLASH_CACHEDIR, FBSPLASH_TMPDIR, MNT_DETACH, and fbspl_cfg_t::profile.
int fbsplash_cache_prep (void)
Prepare a writable splash cache.
Returns:
0 on success, -1 in case of a failure.
References FBSPLASH_CACHEDIR.
int fbsplash_check_daemon (int * pid_daemon)
Check that the splash daemon is running.
Parameters:
pid_daemon Will be set to the PID of the splash daemon if it is found to be running.
Returns:
0 if the splash daemon is running, a negative value otherwise.
References FBSPLASH_PIDFILE.
int fbsplash_check_sanity (void)
Perform sanity checks to make sure that it's safe to start the splash daemon.
Returns:
0 if it's OK to start the daemon, a negative value otherwise.
References fbspl_cfg_t::insane.
void fbsplash_get_res (const char * theme, int * xres, int * yres)
Get the resolution that the splash screen will use.
Parameters:
theme Theme name.
xres Preferred horizontal resolution (e.g. fb_var.xres).
yres Preferred vertical resolution (e.g. fb_var.yres).
Returns:
The resolution that the splash will use is saved in xres and yres. If an error is encountered, xres and yres will be set to 0.
References FBSPL_THEME_DIR.
Referenced by fbsplashr_theme_load().
bool fbsplash_is_silent (void)
Check whether the silent splash screen is being displayed.
Returns:
True if the silent splash is displayed, false otherwise.
References fd_tty0, and fbspl_cfg_t::tty_s.
int fbsplash_lib_cleanup (void)
Clean up after splash_lib_init() and subsequent calls to any libsplash routines.
References fd_tty0, fbspl_cfg_t::message, fbspl_cfg_t::theme, and fbspl_cfg_t::xservice.
fbspl_cfg_t* fbsplash_lib_init (fbspl_type_t type)
Init the splash library.
Parameters:
type One of: spl_undef, spl_bootup, spl_reboot, spl_shutdown
Returns:
Pointer to a config structure used by all routines in libsplash. You should not attempt to free this pointer. If a fbsplash_acc_* function exists to set a members of this config structure, use it instead of setting the member directly.
References config, and fd_tty0.
int fbsplash_parse_kcmdline (bool sysmsg)
Parse the kernel command line to get splash settings and save them in 'config'.
Parameters:
sysmsg If true, the command line will be scanned for the BOOT_MSG splash message override.
Returns:
0 if the command line was parsed correctly, a negative value if there was an error.
References fbspl_cfg_t::effects, FBSPL_EFF_FADEIN, FBSPL_EFF_FADEOUT, FBSPL_MODE_OFF, FBSPL_MODE_SILENT, FBSPL_MODE_VERBOSE, fbsplash_acc_message_set(), fbsplash_acc_theme_set(), fbspl_cfg_t::insane, fbspl_cfg_t::kdmode, fbspl_cfg_t::profile, fbspl_cfg_t::reqmode, and fbspl_cfg_t::tty_s.
int fbsplash_profile (const char * fmt, ...)
Save splash profiling data.
Parameters:
fmt Format of the data to be saved (printf style).
References FBSPLASH_PROFILE, and fbspl_cfg_t::profile.
Referenced by fbsplash_send().
int fbsplash_send (const char * fmt, ...)
Send stuff to the splash daemon using the splash FIFO.
Parameters:
fmt Format of the data to be sent (printf style).
References FBSPLASH_FIFO, and fbsplash_profile().
Referenced by fbsplash_set_evdev(), and fbsplash_set_silent().
int fbsplash_set_evdev (void)
Try to set the event device for the splash daemon.
Returns:
0 if an appropriate event device has been found, a negative value otherwise.
References fbsplash_send().
int fbsplash_set_silent (void)
Switch to silent mode.
Returns:
Previous tty if successful, a negative value otherwise.
References fbsplash_send(), fd_tty0, and fbspl_cfg_t::tty_s.
int fbsplash_set_verbose (int old_tty)
Switch to verbose mode.
Parameters:
old_tty If larger than 0, switch to old_tty instead of the verbose tty defined by config.tty_v.
References fd_tty0, and fbspl_cfg_t::tty_v.
void fbsplashr_cleanup (void)
Cleanup after fbsplashr_init() and subsequent calls to any libsplashrender routines.
References fb_mem, and fd_tty.
int fbsplashr_init (bool create)
Init the splashrender library.
Parameters:
create Create device nodes if they're missing.
References config, endianess, fd_tty, and fbspl_cfg_t::tty_s.
void fbsplashr_input_cleanup ()
Clean up after fbsplashr_input_init().
unsigned short fbsplashr_input_getkey (bool block)
Wait for a keypress or check whether a key has been pressed.
Parameters:
block If true, this function will block.
Returns:
Key code as defined in linux/input.h, 0 if no key has been pressed or an error occured.
int fbsplashr_input_init ()
Initialize the fbsplash input system.
The fbsplash input uses the Linux event device framework. It will not work if evdev isn't built into the kernel or compiled as a module and loaded prior to calling this function.
Returns:
0 on success, a negative value otherwise.
References INPUT_BASE, and INPUT_MAX.
void fbsplashr_message_set (struct fbspl_theme * theme, const char * msg)
Set a new main message.
Parameters:
theme Theme descriptor.
msg The new main message.
References config, fbsplash_acc_message_set(), and fbspl_cfg_t::message.
void fbsplashr_progress_set (struct fbspl_theme * theme, int progress)
Set a new progress value.
Parameters:
theme Theme descriptor.
progress The new progress value.
References config, FBSPL_PROGRESS_MAX, and fbspl_cfg_t::progress.
int fbsplashr_render_buf (struct fbspl_theme * theme, void * buffer, bool repaint)
Render the splash screen to a buffer.
Parameters:
theme Theme for which the screen is to be rendered.
buffer Buffer when the rendered image is to be stored. The image will be in the same format as that used by the fb device which handles the silent splash tty. The buffer should be long enough to contain the whole image (xres * yres * bytes per pixel) where xres and yres are the horizontal and vertical resolution of the current theme or of the video mode active on the framebuffer device.
repaint The whole screen is rendered if true, only updated parts otherwise.
Returns:
0 on success, a negative value otherwise.
References fbd, and FBSPL_MODE_SILENT.
Referenced by fbsplashr_render_screen().
int fbsplashr_render_screen (struct fbspl_theme * theme, bool repaint, bool bgnd, char effects)
Render the splash directly to the screen.
Parameters:
theme Theme for which the screen is to be rendered.
repaint The whole screeen is rendered if true, only updated parts otherwise.
bgnd Return immediately if true, wait for all effects to be rendered otherwise. Effects such as fadein/fadeout take some time to be fully displayed. If this parameter is set to true, they will be rendered from a separate, forked process.
effects Indicates which effects are to be used to display the image. Valid values are constants prefixed with SPL_EFF_.
Returns:
0 on success, a negative value otherwise.
References fb_mem, fbd, FBSPL_EFF_FADEIN, FBSPL_EFF_FADEOUT, fbsplashr_render_buf(), and fd_fb.
void fbsplashr_theme_free (struct fbspl_theme * theme)
Free a theme descriptor struct returned by fbsplashr_theme_load().
Parameters:
theme Theme descriptor to be freed.
struct fbspl_theme* fbsplashr_theme_load () [read]
Load a splash theme specified by config.theme.
Returns:
A pointer to a theme descriptor, which is then passed to any libfbsplashrender functions.
References config, fbd, FBSPL_MODE_SILENT, FBSPL_MODE_VERBOSE, FBSPL_THEME_DIR, fbsplash_get_res(), fbspl_cfg_t::reqmode, and fbspl_cfg_t::theme.
int fbsplashr_tty_silent_cleanup (void)
Restore the silent tty to its previous settings after a call to fbsplashr_tty_silent_init().
References config, fd_tty, and fbspl_cfg_t::tty_s.
int fbsplashr_tty_silent_init (bool clear)
Prepare the silent tty (config.tty_s) for displaying the silent splash screen.
Parameters:
clear If true, the silent tty will be cleared from any text it might contain.
References config, fd_tty, and fbspl_cfg_t::tty_s.
int fbsplashr_tty_silent_set (int tty)
Set a new silent tty.
Parameters:
tty The new silent tty.
References config, fd_tty, and fbspl_cfg_t::tty_s.
int fbsplashr_tty_silent_update (void)
Update all internal settings related to the silent tty.
To be called when switching to the silent tty.
Returns:
0 if all settings have been updated, 1 if the theme has to be reloaded.
References fb_mem, fbd, and fd_fb.