splashutils: libfbsplash.c File Reference
libfbsplash.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <fcntl.h>
#include <termios.h>
#include <unistd.h>
#include <errno.h>
#include <dirent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <sys/mount.h>
#include <linux/fs.h>
#include "common.h"
Defines
#define MNT_DETACH 2
#define FBSPLASH_TMPDIR FBSPLASH_DIR"/tmp"
Functions
fbspl_cfg_t * fbsplash_lib_init (fbspl_type_t type)
int fbsplash_lib_cleanup (void)
int fbsplash_parse_kcmdline (bool sysmsg)
int fbsplash_set_verbose (int old_tty)
bool fbsplash_is_silent (void)
void fbsplash_get_res (const char *theme, int *xres, int *yres)
void fbsplash_acc_theme_set (const char *theme)
void fbsplash_acc_message_set (const char *msg)
void fbsplash_acc_xservice_set (const char *service)
int fbsplash_set_silent ()
int fbsplash_cache_prep (void)
int fbsplash_cache_cleanup (char **profile_save)
int fbsplash_check_daemon (int *pid_daemon)
int fbsplash_check_sanity (void)
int fbsplash_set_evdev (void)
int fbsplash_profile (const char *fmt,...)
int fbsplash_send (const char *fmt,...)
Variables
int fd_tty0 = -1
fbspl_cfg_t config
Define Documentation
#define FBSPLASH_TMPDIR FBSPLASH_DIR"/tmp"
Referenced by fbsplash_cache_cleanup().
#define MNT_DETACH 2
Referenced by fbsplash_cache_cleanup().
Function Documentation
void fbsplash_acc_message_set (const char * msg)
Accessor function for config.message
Parameters:
msg The new message setting.
References fbspl_cfg_t::message.
Referenced by fbsplash_parse_kcmdline(), and fbsplashr_message_set().
void fbsplash_acc_theme_set (const char * theme)
Accessor function for config.theme
Parameters:
theme The new theme setting.
References fbspl_cfg_t::theme.
Referenced by fbsplash_parse_kcmdline().
void fbsplash_acc_xservice_set (const char * service)
Accessor function for config.xservice
Parameters:
service The name of the new X service.
References fbspl_cfg_t::xservice.
int fbsplash_cache_cleanup (char ** profile_save)
Clean the splash cache.
Parameters:
profile_save A strlist of files that should be saved to the hdd if profiling is enabled.
Returns:
0 if the splash cache was cleaned, a negative value in case of an error.
References FBSPLASH_CACHEDIR, FBSPLASH_TMPDIR, MNT_DETACH, and fbspl_cfg_t::profile.
int fbsplash_cache_prep (void)
Prepare a writable splash cache.
Returns:
0 on success, -1 in case of a failure.
References FBSPLASH_CACHEDIR.
int fbsplash_check_daemon (int * pid_daemon)
Check that the splash daemon is running.
Parameters:
pid_daemon Will be set to the PID of the splash daemon if it is found to be running.
Returns:
0 if the splash daemon is running, a negative value otherwise.
References FBSPLASH_PIDFILE.
int fbsplash_check_sanity (void)
Perform sanity checks to make sure that it's safe to start the splash daemon.
Returns:
0 if it's OK to start the daemon, a negative value otherwise.
References fbspl_cfg_t::insane.
void fbsplash_get_res (const char * theme, int * xres, int * yres)
Get the resolution that the splash screen will use.
Parameters:
theme Theme name.
xres Preferred horizontal resolution (e.g. fb_var.xres).
yres Preferred vertical resolution (e.g. fb_var.yres).
Returns:
The resolution that the splash will use is saved in xres and yres. If an error is encountered, xres and yres will be set to 0.
References FBSPL_THEME_DIR.
Referenced by fbsplashr_theme_load().
bool fbsplash_is_silent (void)
Check whether the silent splash screen is being displayed.
Returns:
True if the silent splash is displayed, false otherwise.
References fd_tty0, and fbspl_cfg_t::tty_s.
int fbsplash_lib_cleanup (void)
Clean up after splash_lib_init() and subsequent calls to any libsplash routines.
References fd_tty0, fbspl_cfg_t::message, fbspl_cfg_t::theme, and fbspl_cfg_t::xservice.
fbspl_cfg_t* fbsplash_lib_init (fbspl_type_t type)
Init the splash library.
Parameters:
type One of: spl_undef, spl_bootup, spl_reboot, spl_shutdown
Returns:
Pointer to a config structure used by all routines in libsplash. You should not attempt to free this pointer. If a fbsplash_acc_* function exists to set a members of this config structure, use it instead of setting the member directly.
References config, and fd_tty0.
int fbsplash_parse_kcmdline (bool sysmsg)
Parse the kernel command line to get splash settings and save them in 'config'.
Parameters:
sysmsg If true, the command line will be scanned for the BOOT_MSG splash message override.
Returns:
0 if the command line was parsed correctly, a negative value if there was an error.
References fbspl_cfg_t::effects, FBSPL_EFF_FADEIN, FBSPL_EFF_FADEOUT, FBSPL_MODE_OFF, FBSPL_MODE_SILENT, FBSPL_MODE_VERBOSE, fbsplash_acc_message_set(), fbsplash_acc_theme_set(), fbspl_cfg_t::insane, fbspl_cfg_t::kdmode, fbspl_cfg_t::profile, fbspl_cfg_t::reqmode, and fbspl_cfg_t::tty_s.
int fbsplash_profile (const char * fmt, ...)
Save splash profiling data.
Parameters:
fmt Format of the data to be saved (printf style).
References FBSPLASH_PROFILE, and fbspl_cfg_t::profile.
Referenced by fbsplash_send().
int fbsplash_send (const char * fmt, ...)
Send stuff to the splash daemon using the splash FIFO.
Parameters:
fmt Format of the data to be sent (printf style).
References FBSPLASH_FIFO, and fbsplash_profile().
Referenced by fbsplash_set_evdev(), and fbsplash_set_silent().
int fbsplash_set_evdev (void)
Try to set the event device for the splash daemon.
Returns:
0 if an appropriate event device has been found, a negative value otherwise.
References fbsplash_send().
int fbsplash_set_silent (void)
Switch to silent mode.
Returns:
Previous tty if successful, a negative value otherwise.
References fbsplash_send(), fd_tty0, and fbspl_cfg_t::tty_s.
int fbsplash_set_verbose (int old_tty)
Switch to verbose mode.
Parameters:
old_tty If larger than 0, switch to old_tty instead of the verbose tty defined by config.tty_v.
References fd_tty0, and fbspl_cfg_t::tty_v.
Variable Documentation
fbspl_cfg_t config
Referenced by fbsplash_lib_init(), fbsplashr_init(), fbsplashr_message_set(), fbsplashr_progress_set(), fbsplashr_theme_load(), fbsplashr_tty_silent_cleanup(), fbsplashr_tty_silent_init(), and fbsplashr_tty_silent_set().
int fd_tty0 = -1
Referenced by fbsplash_is_silent(), fbsplash_lib_cleanup(), fbsplash_lib_init(), fbsplash_set_silent(), and fbsplash_set_verbose().